name: CI & Publish Pipeline

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Lint, Typecheck, and Tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Run Tests and generate report
        run: npm run test:ci

      - name: Publish Test Report to GitHub UI
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Mocha Tests
          path: results/test-results.xml
          reporter: mocha-junit

  build:
    runs-on: ubuntu-latest
    name: Build the Project
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  publish:
    runs-on: ubuntu-latest
    name: Publish to npm
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    environment:
      name: npm-publish
      url: https://www.npmjs.com/package/chrono-utilz

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build (Ensure output before publishing)
        run: npm run prepare

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
